services:
    psql:
        image: postgres:16.3
        restart: no
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - primary
        volumes:
            - "./.volumes/postgresql:/var/lib/postgresql/data"

    api:
        build:
            context: .
            dockerfile: api.Dockerfile
            target: base
        env_file:
            - .env
        ports:
            - "3001:3001"
        command: ./main
        depends_on:
            - psql
        networks:
            - primary

    chrome:
        image: chromedp/headless-shell:latest
        networks:
            - primary
        ports:
            - "9222:9222"

    scraper:
        build:
            context: .
            dockerfile: scraper.Dockerfile
            target: base
        env_file:
            - .env
        command: ./main
        depends_on:
            - chrome
        networks:
            - primary

networks:
    primary:

